name: state_machine_bloc
description: An extension to the bloc state management library which let you create State Machine using a declarative API.
version: 0.0.1-dev.2
homepage: https://github.com/Pierre2tm/state_machine_bloc
repository: https://github.com/Pierre2tm/state_machine_bloc

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0

dependencies: 
  bloc: ^8.0.2
  bloc_concurrency: ^0.2.0
  meta: ^1.7.0
